//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.12 at 06:38:36 ���� CST 
//


package org.neolm.batools.core.job.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JobForRepositoryConfig }
     * 
     */
    public JobForRepositoryConfig createJobForRepositoryConfig() {
        return new JobForRepositoryConfig();
    }

    /**
     * Create an instance of {@link JobForRepositoryConfig.JobParameters }
     * 
     */
    public JobForRepositoryConfig.JobParameters createJobForRepositoryConfigJobParameters() {
        return new JobForRepositoryConfig.JobParameters();
    }

    /**
     * Create an instance of {@link JobForRepositoryConfig.JobParameters.Param }
     * 
     */
    public JobForRepositoryConfig.JobParameters.Param createJobForRepositoryConfigJobParametersParam() {
        return new JobForRepositoryConfig.JobParameters.Param();
    }

    /**
     * Create an instance of {@link JobForRepositoryConfig.IndexFileFilter.IncludeExtension }
     * 
     */
    public JobForRepositoryConfig.IndexFileFilter.IncludeExtension createJobForRepositoryConfigIndexFileFilterIncludeExtension() {
        return new JobForRepositoryConfig.IndexFileFilter.IncludeExtension();
    }

    /**
     * Create an instance of {@link JobForRepositoryConfig.TargetPaths }
     * 
     */
    public JobForRepositoryConfig.TargetPaths createJobForRepositoryConfigTargetPaths() {
        return new JobForRepositoryConfig.TargetPaths();
    }

    /**
     * Create an instance of {@link JobForRepositoryConfig.IndexFileFilter }
     * 
     */
    public JobForRepositoryConfig.IndexFileFilter createJobForRepositoryConfigIndexFileFilter() {
        return new JobForRepositoryConfig.IndexFileFilter();
    }

}
